#spring:
#  datasource:
#    url: jdbc:sqlserver://0.0.0.0:1433;databaseName=Care4You
#    username: sa
#    password: Password1!
#    platform: mssql
#    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    hikari:
#      schema: dbo
#  jpa:
#    hibernate:
#      ddl-auto: none
#    database: SQL_SERVER
#    show-sql: true

spring:
  application:
    name: care-for-you-persistence
  data:
    mongodb:
      uri: mongodb://localhost:27017/Care4You